apiVersion: v1
kind: ConfigMap
metadata:
  name: mediot-config
  namespace: mediot
data:
  KAFKA_BROKER: "kafka-service.mediot.svc.cluster.local:9092"
  DATABASE_HOST: "mediot-postgres.c6nn6rqlgxwa.us-east-1.rds.amazonaws.com"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "mediot"
  FRONTEND_URL: "http://a2c00119273a444f4828ef8036ee7476-825493860.us-east-1.elb.amazonaws.com"
