apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mediot-secrets
  namespace: mediot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mediot-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: mediot/database_url
    - secretKey: API_KEY
      remoteRef:
        key: mediot/api_key
    - secretKey: JWT_SECRET
      remoteRef:
        key: mediot/jwt_secret
    - secretKey: OAUTH_GOOGLE_CLIENT_ID
      remoteRef:
        key: mediot/oauth_google_client_id
    - secretKey: OAUTH_GOOGLE_CLIENT_SECRET
      remoteRef:
        key: mediot/oauth_google_client_secret
    - secretKey: OAUTH_APPLE_CLIENT_ID
      remoteRef:
        key: mediot/oauth_apple_client_id
    - secretKey: OAUTH_APPLE_CLIENT_SECRET
      remoteRef:
        key: mediot/oauth_apple_client_secret
    - secretKey: OAUTH_FACEBOOK_CLIENT_ID
      remoteRef:
        key: mediot/oauth_facebook_client_id
    - secretKey: OAUTH_FACEBOOK_CLIENT_SECRET
      remoteRef:
        key: mediot/oauth_facebook_client_secret
