apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediot-frontend
  namespace: mediot
  labels:
    app: mediot-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mediot-frontend
  template:
    metadata:
      labels:
        app: mediot-frontend
    spec:
      containers:
        - name: frontend
          image: 697957957974.dkr.ecr.us-east-1.amazonaws.com/mediot-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mediot
spec:
  selector:
    app: mediot-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mediot-ingress
  namespace: mediot
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
