apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediot-kafka
  namespace: mediot
  labels:
    app: mediot-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediot-kafka
  template:
    metadata:
      labels:
        app: mediot-kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-service:9092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka/data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: mediot
spec:
  selector:
    app: mediot-kafka
  ports:
    - port: 9092
      targetPort: 9092
  type: ClusterIP
